# Generated by Django 4.2.17 on 2025-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_coffeepost_options_alter_coffeepost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepost',
            name='image_url',
            field=models.CharField(default='coffe_default.jpg', max_length=500),
        ),
    ]
