# Generated by Django 4.2.17 on 2025-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
