# Generated by Django 4.2.17 on 2025-01-09 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_coffeepost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coffeepost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
