# Generated by Django 4.2.17 on 2025-01-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_coffeepost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
