# Generated by Django 5.1.7 on 2025-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_coffeepost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepost',
            name='post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
